### ISSUE TITLE
Audio input

### ISSUE THREAD

**Issue by superpoweredSDK** [KimJeongYeon/jack2_android#1]
Hello,

do you have an estimate when audio input becomes available with Samsung Professional Audio SDK please?

Best regards,

Gábor
CTO, Superpowered

**Comment by KimJeongYeon** [comment]
Hello,

Currently, Samsung Professional Audio SDK supports it.
But, it may works on Samsung's Galaxy Note 4 or newer.
For more detail, I think it is better to contact at http://developer.samsung.com/forum/en?boardName=SDK&searchSubId=0000000019

Regards,
KimJeongYeon

**Comment by superpoweredSDK** [comment]
Thank you, i will ask there.

**Comment by superpoweredSDK** [comment]
Unfortunately, there is no official answer on that forum.
